# Generated by Django 3.2.7 on 2021-09-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_log_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isPaused',
            field=models.BooleanField(default=False),
        ),
    ]
