# Generated by Django 3.0.6 on 2020-05-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oneauth_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
